<h1 style="background-color: #f0f8ff; padding: 10px; border-radius: 8px; text-align:center;">
Pandas
</h1>

---

## OBJETIVO:

🎯 Objetivos de la clase de Pandas

- Comprender las estructuras de datos de Pandas
- Crear y manipular Series y DataFrames
- Seleccionar y filtrar información
- Aplicar operaciones básicas sobre datos
- Trabajar con datos faltantes y limpiar información
- Analizar y resumir información
- Relacionar múltiples conjuntos de datos
- Aplicar Pandas en ejercicios prácticos

# Pandas 
Es una de las librerías más populares en Python para **análisis y manipulación de datos.**
Permite trabajar con estructuras de datos muy eficientes como:

- Series: similares a un array unidimensional.

- DataFrames: tablas bidimensionales (filas y columnas), muy parecidas a las de Excel o SQL.

# Instalación y uso básico

In [3]:
# Instalación (solo si no lo tienes)
# !pip install pandas

# Importación
import pandas as pd
import numpy as np

# 1. Series en Pandas

## 1.1 Creacion

In [4]:
# Desde lista
s = pd.Series([10, 20, 30])
print(s)

0    10
1    20
2    30
dtype: int64

In [5]:
# Con índices personalizados
s2 = pd.Series([100,200,300], index=['a','b','c'])
print(s2)

a    100
b    200
c    300
dtype: int64

In [6]:
# Desde diccionario
d = {'x':1, 'y':2, 'z':3}
s3 = pd.Series(d)
print(s3)

x    1
y    2
z    3
dtype: int64

## 1.2 Operaciones

In [7]:
s = pd.Series([1,2,3,4])

In [8]:
s

0    1
1    2
2    3
3    4
dtype: int64

In [9]:
print(s + 10)

0    11
1    12
2    13
3    14
dtype: int64

In [10]:
print(s * 2)

0    2
1    4
2    6
3    8
dtype: int64

In [11]:
print(np.sqrt(s))

0    1.000000
1    1.414214
2    1.732051
3    2.000000
dtype: float64

# 2 Dataframes

## 2.1 Creacion

In [12]:
data = {'Nombre': ['Ana','Juan','Pedro'], 'Edad':[23,35,29], 'Ciudad':['Santiago','Valparaíso','Concepción']}
df = pd.DataFrame(data)
print(df)

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

In [13]:
df_copia = df.copy()
df_copia

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

## 2.2 Inspección

In [14]:
# primeras filas
print(df.head(2))

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso

In [15]:
# últimas filas
print(df.tail(2))

  Nombre  Edad      Ciudad
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

In [16]:
# información object son textos 
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nombre  3 non-null      object
 1   Edad    3 non-null      int64
 2   Ciudad  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 200.0+ bytes
None

In [17]:
# estadísticas
print(df.describe())

       Edad
count   3.0
mean   29.0
std     6.0
min    23.0
25%    26.0
50%    29.0
75%    32.0
max    35.0

In [18]:
# dimensiones
print(df.shape)

(3, 3)

In [19]:
# columnas
print(df.columns)

Index(['Nombre', 'Edad', 'Ciudad'], dtype='object')

In [20]:
# índices
print(df.index)

RangeIndex(start=0, stop=3, step=1)

## 2.3 Selección de datos

In [21]:
df

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

In [22]:
# Columnas
print(df['Nombre'])

0      Ana
1     Juan
2    Pedro
Name: Nombre, dtype: object

In [23]:
df['Nombre']

0      Ana
1     Juan
2    Pedro
Name: Nombre, dtype: object

In [24]:
# Columnas
print(df[['Nombre','Edad']])

  Nombre  Edad
0    Ana    23
1   Juan    35
2  Pedro    29

In [25]:
# Filas por posición
print(df.iloc[0])
print(df.iloc[0:2])

Nombre         Ana
Edad            23
Ciudad    Santiago
Name: 0, dtype: object
  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso

In [26]:
# Filas por índice
print(df.loc[0])
print(df.loc[0:1])

Nombre         Ana
Edad            23
Ciudad    Santiago
Name: 0, dtype: object
  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso

In [27]:
# Condiciones
print(df[df['Edad'] > 25])

  Nombre  Edad      Ciudad
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

In [28]:
print(df[(df['Edad']>25) & (df['Ciudad']=='Concepción')])

  Nombre  Edad      Ciudad
2  Pedro    29  Concepción

# 3. Operaciones con DataFrames

## 3.1 Operaciones aritméticas

In [29]:
df

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

In [30]:
df['Total'] = df['Edad'] * 2
print(df)

  Nombre  Edad      Ciudad  Total
0    Ana    23    Santiago     46
1   Juan    35  Valparaíso     70
2  Pedro    29  Concepción     58

## 3.2 Funciones estadísticas

In [31]:
# Promedio
print(df['Edad'].mean())

29.0

In [32]:
# Suma
print(df['Edad'].sum())

87

In [33]:
# Minimo
print(df['Edad'].min())

23

In [34]:
# Maximo
print(df['Edad'].max())

35

## 3.3 Nuevas columnas

In [35]:
# Datos
data = {'Nombre': ['Ana','Juan','Pedro'], 'Edad':[23,35,29], 'Ciudad':['Santiago','Valparaíso','Concepción']}
df = pd.DataFrame(data)
print(df)

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

In [36]:
# Nueva columna valor fijo
df['Pais'] = "Chile"
print(df)

  Nombre  Edad      Ciudad   Pais
0    Ana    23    Santiago  Chile
1   Juan    35  Valparaíso  Chile
2  Pedro    29  Concepción  Chile

In [37]:
# Nueva columna valor fijo
df['Edad_doble'] = df['Edad'] *2
print(df)

  Nombre  Edad      Ciudad   Pais  Edad_doble
0    Ana    23    Santiago  Chile          46
1   Juan    35  Valparaíso  Chile          70
2  Pedro    29  Concepción  Chile          58

In [38]:
# Nueva columna valor fijo
df['Edad_total'] = sum(df['Edad'])
print(df)

  Nombre  Edad      Ciudad   Pais  Edad_doble  Edad_total
0    Ana    23    Santiago  Chile          46          87
1   Juan    35  Valparaíso  Chile          70          87
2  Pedro    29  Concepción  Chile          58          87

In [39]:
# Nueva columna Booleana
df['Mayor_30'] = df['Edad'] > 30
print(df)

  Nombre  Edad      Ciudad   Pais  Edad_doble  Edad_total  Mayor_30
0    Ana    23    Santiago  Chile          46          87     False
1   Juan    35  Valparaíso  Chile          70          87      True
2  Pedro    29  Concepción  Chile          58          87     False

# 4. Manejo de valores faltantes

In [40]:
df2 = pd.DataFrame({'A':[1,np.nan,3], 'B':[4,5,np.nan]})
print(df2)

     A    B
0  1.0  4.0
1  NaN  5.0
2  3.0  NaN

In [41]:
# Detectar NaN
print(df2.isna())

       A      B
0  False  False
1   True  False
2  False   True

In [42]:
# Eliminar NaN
print(df2.dropna())

     A    B
0  1.0  4.0

In [43]:
# Rellenar NaN
print(df2.fillna(0))

df2

     A    B
0  1.0  4.0
1  0.0  5.0
2  3.0  0.0

     A    B
0  1.0  4.0
1  NaN  5.0
2  3.0  NaN

In [44]:
# Rellenar NaN
print(df2.fillna(df2.mean()))

     A    B
0  1.0  4.0
1  2.0  5.0
2  3.0  4.5

In [45]:
# Datos
data = {'Nombre': ['Ana','Juan','Pedro'], 'Edad':[23,35,np.nan], 'Sueldo':[100,np.nan,300]}
df = pd.DataFrame(data)
print(df)

  Nombre  Edad  Sueldo
0    Ana  23.0   100.0
1   Juan  35.0     NaN
2  Pedro   NaN   300.0

In [46]:
print(df.fillna({'Edad': df['Edad'].mean(), 'Sueldo': df['Sueldo'].max()}))

  Nombre  Edad  Sueldo
0    Ana  23.0   100.0
1   Juan  35.0   300.0
2  Pedro  29.0   300.0

# 5. Indexación avanzada

In [47]:
# Datos
data = {'Nombre': ['Ana','Juan','Pedro'], 'Edad':[23,35,29], 'Ciudad':['Santiago','Valparaíso','Concepción']}
df = pd.DataFrame(data)
print(df)

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

## 5.1 Set Index

In [48]:
df.set_index('Nombre', inplace=True)
print(df)

        Edad      Ciudad
Nombre
Ana       23    Santiago
Juan      35  Valparaíso
Pedro     29  Concepción

In [49]:
## 5.2 Reset Index

In [50]:
df.reset_index(inplace=True)
print(df)

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

# 6. Ordenar y filtrar

In [51]:
# Datos
data = {'Nombre': ['Ana','Juan','Pedro'], 'Edad':[23,35,29], 'Ciudad':['Santiago','Valparaíso','Concepción']}
df = pd.DataFrame(data)
print(df)

  Nombre  Edad      Ciudad
0    Ana    23    Santiago
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

In [52]:
# Ordenar por columna
df_sorted = df.sort_values(by='Edad', ascending=False)
print(df_sorted)

  Nombre  Edad      Ciudad
1   Juan    35  Valparaíso
2  Pedro    29  Concepción
0    Ana    23    Santiago

In [53]:
# Ordenar por múltiples columnas
df_sorted2 = df.sort_values(by=['Ciudad','Edad'], ascending=[True, False])
print(df_sorted2)

  Nombre  Edad      Ciudad
2  Pedro    29  Concepción
0    Ana    23    Santiago
1   Juan    35  Valparaíso

In [54]:
# Filtrar
df_filtrado = df[df['Nombre'] == 'Juan']
print(df_filtrado)

  Nombre  Edad      Ciudad
1   Juan    35  Valparaíso

In [55]:
# Filtrar
filtrado = df[df['Edad'] >= 25]
print(filtrado)

  Nombre  Edad      Ciudad
1   Juan    35  Valparaíso
2  Pedro    29  Concepción

In [56]:
# Filtrar
filtrado = df[ (df['Nombre'] == 'Juan') & (df['Edad'] >= 25) ]
print(filtrado)

  Nombre  Edad      Ciudad
1   Juan    35  Valparaíso

# 7. Agrupamiento (GroupBy)

In [57]:
# Datos
data = {'Ciudad':['Santiago','Valparaíso','Santiago','Concepción','Valparaíso'],
        'Ventas':[100,200,150,300,120]}
df3 = pd.DataFrame(data)
df3

       Ciudad  Ventas
0    Santiago     100
1  Valparaíso     200
2    Santiago     150
3  Concepción     300
4  Valparaíso     120

## 7.1 Agrupar por 1 columna

In [58]:
# Agrupar y sumar
print(df3.groupby('Ciudad').sum())

            Ventas
Ciudad
Concepción     300
Santiago       250
Valparaíso     320

In [59]:
# Agrupar y promedio
print(df3.groupby('Ciudad').mean())

            Ventas
Ciudad
Concepción   300.0
Santiago     125.0
Valparaíso   160.0

In [60]:
# Agrupar y Contar registros
print(df3.groupby('Ciudad').count())

            Ventas
Ciudad
Concepción       1
Santiago         2
Valparaíso       2

## 7.2 Agrupar por mas de 1 columna

In [61]:
# Datos
data = {
    'Departamento': ['Ventas', 'Ventas', 'TI', 'TI', 'Ventas', 'TI'],
    'Ciudad': ['Madrid', 'Barcelona', 'Madrid', 'Barcelona', 'Madrid', 'Barcelona'],
    'Ventas': [100, 150, 200, 250, 300, 350],
    'Empleados': [5, 3, 8, 6, 7, 4]
}

df = pd.DataFrame(data)
print(df)

  Departamento     Ciudad  Ventas  Empleados
0       Ventas     Madrid     100          5
1       Ventas  Barcelona     150          3
2           TI     Madrid     200          8
3           TI  Barcelona     250          6
4       Ventas     Madrid     300          7
5           TI  Barcelona     350          4

### 7.2.1 Agrupar y Contar

In [62]:
# Contar registros por Departamento y Ciudad
conteo = df.groupby(['Departamento', 'Ciudad']).size()
print(conteo)

Departamento  Ciudad
TI            Barcelona    2
              Madrid       1
Ventas        Barcelona    1
              Madrid       2
dtype: int64

In [63]:
# Contar registros por Departamento y Ciudad
conteo = df.groupby(['Ciudad','Departamento']).size()
print (conteo)

Ciudad     Departamento
Barcelona  TI              2
           Ventas          1
Madrid     TI              1
           Ventas          2
dtype: int64

### 7.2.2 Agrupar y Sumar

In [64]:
# Agrupar por Departamento y Ciudad, y sumar las ventas
grupo = df.groupby(['Departamento', 'Ciudad'])['Ventas'].sum()
print(grupo)

Departamento  Ciudad
TI            Barcelona    600
              Madrid       200
Ventas        Barcelona    150
              Madrid       400
Name: Ventas, dtype: int64

### 7.2.3 Agrupar y aplicar múltiples operaciones

In [65]:
# Agrupar por dos columnas y aplicar diferentes operaciones
resultado = df.groupby(['Departamento', 'Ciudad']).agg({
    'Ventas': ['sum', 'mean'],  # Suma y promedio de ventas
    'Empleados': 'mean'         # Promedio de empleados
})
print(resultado)

                       Ventas        Empleados
                          sum   mean      mean
Departamento Ciudad
TI           Barcelona    600  300.0       5.0
             Madrid       200  200.0       8.0
Ventas       Barcelona    150  150.0       3.0
             Madrid       400  200.0       6.0

### 7.2.4 Agrupar con reset_index()

A menudo, es útil convertir el MultiIndex en columnas regulares. Se puede lograr esto encadenando el método .reset_index() al final.

In [66]:
# Agrupar por Departamento y Ciudad, y sumar las ventas
grupo = df.groupby(['Departamento', 'Ciudad'])['Ventas'].sum().reset_index()
grupo

  Departamento     Ciudad  Ventas
0           TI  Barcelona     600
1           TI     Madrid     200
2       Ventas  Barcelona     150
3       Ventas     Madrid     400

# 8. Merge y Concatenación

In [67]:
# Datos
df1 = pd.DataFrame({'ID':[1,2,3], 'Nombre':['Ana','Juan','Pedro']})
df2 = pd.DataFrame({'ID':[2,3,4], 'Ciudad':['Valpo','Conce','Santi']})

print (df1)
print ("-------------")
print (df2)

   ID Nombre
0   1    Ana
1   2   Juan
2   3  Pedro
-------------
   ID Ciudad
0   2  Valpo
1   3  Conce
2   4  Santi

In [68]:
# Merge inner
print(pd.merge(df1, df2, on='ID', how='inner'))

   ID Nombre Ciudad
0   2   Juan  Valpo
1   3  Pedro  Conce

In [69]:
# Merge left
print(pd.merge(df1, df2, on='ID', how='left'))

   ID Nombre Ciudad
0   1    Ana    NaN
1   2   Juan  Valpo
2   3  Pedro  Conce

In [70]:
# Concatenar verticalmente
print(pd.concat([df1, df2], ignore_index=True))

   ID Nombre Ciudad
0   1    Ana    NaN
1   2   Juan    NaN
2   3  Pedro    NaN
3   2    NaN  Valpo
4   3    NaN  Conce
5   4    NaN  Santi

# 9. Pivot

In [71]:
# Datos
data = {
    'Producto': ['Manzana', 'Uva', 'Manzana', 'Uva', 'Palta', 'Palta', 'Manzana'],
    'Ciudad': ['Santiago', 'Santiago', 'Valparaíso', 'Valparaíso', 'Santiago', 'Concepción', 'Concepción'],
    'Ventas': [100, 150, 200, 250, 300, 350, 400],
    'Clientes': [5, 3, 8, 6, 7, 4, 9]
}
df = pd.DataFrame(data)
print(df)

  Producto      Ciudad  Ventas  Clientes
0  Manzana    Santiago     100         5
1      Uva    Santiago     150         3
2  Manzana  Valparaíso     200         8
3      Uva  Valparaíso     250         6
4    Palta    Santiago     300         7
5    Palta  Concepción     350         4
6  Manzana  Concepción     400         9

In [72]:
# Productos como filas, Ciudades como columnas, Ventas como valores
pivot1 = df.pivot(index='Producto', columns='Ciudad', values='Ventas')
print("\n1. Ventas por Producto y Ciudad:")
print(pivot1)

1. Ventas por Producto y Ciudad:
Ciudad    Concepción  Santiago  Valparaíso
Producto
Manzana        400.0     100.0       200.0
Palta          350.0     300.0         NaN
Uva              NaN     150.0       250.0

In [73]:
# Múltiples medidas (Ventas y Clientes)
pivot2 = df.pivot(index='Producto', columns='Ciudad', values=['Ventas', 'Clientes'])
print("\n2. Ventas y Clientes por Producto y Ciudad:")
print(pivot2)

2. Ventas y Clientes por Producto y Ciudad:
             Ventas                       Clientes
Ciudad   Concepción Santiago Valparaíso Concepción Santiago Valparaíso
Producto
Manzana       400.0    100.0      200.0        9.0      5.0        8.0
Palta         350.0    300.0        NaN        4.0      7.0        NaN
Uva             NaN    150.0      250.0        NaN      3.0        6.0

In [74]:
# pivot_table con múltiples funciones
pivot4 = df.pivot_table(
    index='Producto',
    columns='Ciudad',
    values='Ventas',
    aggfunc=['sum', 'mean', 'count'],  # Suma, promedio y conteo
    fill_value=0
)
print("\n4. Diferentes estadísticas por ciudad:")
pivot4

4. Diferentes estadísticas por ciudad:

                sum                           mean                      \
Ciudad   Concepción Santiago Valparaíso Concepción Santiago Valparaíso
Producto
Manzana         400      100        200      400.0    100.0      200.0
Palta           350      300          0      350.0    300.0        0.0
Uva               0      150        250        0.0    150.0      250.0

              count
Ciudad   Concepción Santiago Valparaíso
Producto
Manzana           1        1          1
Palta             1        1          0
Uva               0        1          1

In [75]:
# Para incluir todas las ciudades aunque no tengan datos
pivot5 = df.pivot_table(
    index='Producto',
    columns='Ciudad',
    values='Ventas',
    aggfunc='sum',
    fill_value=0
)
print("\n5. Ventas con todas las ciudades (fill_value=0):")
print(pivot5)

5. Ventas con todas las ciudades (fill_value=0):
Ciudad    Concepción  Santiago  Valparaíso
Producto
Manzana          400       100         200
Palta            350       300           0
Uva                0       150         250

In [76]:
import pandas as pd

# Datos con duplicados: Manzana-Santiago aparece 2 veces
data = {
    'Producto': ['Manzana', 'Manzana', 'Uva', 'Manzana'],
    'Ciudad': ['Santiago', 'Santiago', 'Valparaíso', 'Santiago'],
    'Ventas': [100, 50, 200, 75]
}

df = pd.DataFrame(data)
print("Datos con duplicados:")
print(df)

Datos con duplicados:
  Producto      Ciudad  Ventas
0  Manzana    Santiago     100
1  Manzana    Santiago      50
2      Uva  Valparaíso     200
3  Manzana    Santiago      75

In [77]:
# ERROR: No se puede pivotar porque hay valores duplicados
# df.pivot(index='Producto', columns='Ciudad', values='Ventas')

In [78]:
# Suma los valores duplicados: 100 + 50 + 75 = 225 para Manzana-Santiago
pivot_sum = df.pivot_table(
    index='Producto', 
    columns='Ciudad', 
    values='Ventas', 
    aggfunc='sum'  # ← Suma los duplicados
)
print("Suma de ventas (agrega duplicados):")
print(pivot_sum)

Suma de ventas (agrega duplicados):
Ciudad    Santiago  Valparaíso
Producto
Manzana      225.0         NaN
Uva            NaN       200.0

# 10. Lectura y escritura de archivos

In [79]:
import pandas as pd
data = {
    'Producto': ['Manzana', 'Uva', 'Manzana', 'Uva', 'Palta', 'Palta', 'Manzana'],
    'Ciudad': ['Santiago', 'Santiago', 'Valparaíso', 'Valparaíso', 'Santiago', 'Concepción', 'Concepción'],
    'Ventas': [100, 150, 200, 250, 300, 350, 400],
    'Clientes': [5, 3, 8, 6, 7, 4, 9]
}
df = pd.DataFrame(data)
df

  Producto      Ciudad  Ventas  Clientes
0  Manzana    Santiago     100         5
1      Uva    Santiago     150         3
2  Manzana  Valparaíso     200         8
3      Uva  Valparaíso     250         6
4    Palta    Santiago     300         7
5    Palta  Concepción     350         4
6  Manzana  Concepción     400         9

## 10.1 CSV

La función `read_csv` La función tiene muchos argumentos opcionales (más de 50). Es imposible memorizarlos a todos; por lo general, es mejor buscar la funcionalidad particular cuando se necesite.

Se puede buscar por  `pandas read_csv` en internet para buscar la documentación.

También hay muchas otras funciones que pueden leer datos. Algunos ejemplos:

| Función | Descripción
| -- | -- |
| read_csv       | Cargue datos delimitados de un archivo, URL u objeto similar. El delimitador predeterminado es una coma. `,` |
| read_table     | Cargue datos delimitados de un archivo, URL u objeto similar. El delimitador predeterminado es tab `\t` |
| read_clipboard | Lee el último objeto que ha copiado (Ctrl-C) |
| read_excel     | Leer datos tabulares del archivo Excel .XLS o .XLSX |
| read_hdf       | Leer archivos HDF5 escrito por pandas |
| read_html      | Leer todas las tablas encontradas en el documento HTML dado |
| read_json      | Leer datos de una cadena JSON |
| read_sql       | Leer los resultados de una consulta SQL |

*Nota: también hay otras funciones de carga que no se mencionan aquí*

In [80]:
df.to_csv('mi_dataframe.csv', index=False,sep=";") # Guardar archivo

In [81]:
df_leido = pd.read_csv('mi_dataframe.csv',sep=";") # Leer archivo guardado
df_leido

  Producto      Ciudad  Ventas  Clientes
0  Manzana    Santiago     100         5
1      Uva    Santiago     150         3
2  Manzana  Valparaíso     200         8
3      Uva  Valparaíso     250         6
4    Palta    Santiago     300         7
5    Palta  Concepción     350         4
6  Manzana  Concepción     400         9

## 10.2 Excel

openpyxl no está instalado por defecto en Python. Es una librería de terceros que se usa para leer y escribir archivos de Excel (.xlsx).

Para poder usar openpyxl, necesitas instalarla con pip, el gestor de paquetes de Python. Abre tu terminal o símbolo del sistema y ejecuta el siguiente comando: pip install openpyxl

In [82]:
# !pip install openpyxl
import openpyxl

df.to_excel('mi_dataframe.xlsx', index=False) # Guardar archivo

df_excel = pd.read_excel('mi_dataframe.xlsx') # Leer archivo guardado
print(df_excel)

  Producto      Ciudad  Ventas  Clientes
0  Manzana    Santiago     100         5
1      Uva    Santiago     150         3
2  Manzana  Valparaíso     200         8
3      Uva  Valparaíso     250         6
4    Palta    Santiago     300         7
5    Palta  Concepción     350         4
6  Manzana  Concepción     400         9

## 10.3 JSON

In [83]:
df.to_json('mi_dataframe.json') # Guardar archivo

df_json = pd.read_json('mi_dataframe.json') # Leer archivo guardado
print(df_json)

  Producto      Ciudad  Ventas  Clientes
0  Manzana    Santiago     100         5
1      Uva    Santiago     150         3
2  Manzana  Valparaíso     200         8
3      Uva  Valparaíso     250         6
4    Palta    Santiago     300         7
5    Palta  Concepción     350         4
6  Manzana  Concepción     400         9