<table>
  <tr>
      <td>
          <h1 style="text-align:center"></h1>
      </td>
  </tr>
  <tr>
    <td>
        <h1 style="text-align:center">Numpy</h1>
      </td>
  </tr>
</table>

[NumPy] (http://numpy.org), abreviatura de Numerical Python, ha sido durante mucho tiempo la piedra angular de la computación numérica en Python. Proporciona estructuras de datos, algoritmos y es el ingrediente necesario para la mayoría de las aplicaciones científicas que involucran datos numéricos en Python. Todo el cálculo se realiza en forma vectorizada. NumPy contiene, entre otras cosas:
* Un objeto de matriz multidimensional, rápido y eficiente `ndarray`.
* Funciones matemáticas para realizar cálculos con matrices u operaciones matemáticas entre matrices.
* Herramientas para leer y manipular grandes datos de matriz en el disco y trabajar con archivos mapeados en memoria.
* Álgebra lineal, generación de números aleatorios y otros.

Para el resto de este tema, cada vez que se menciona la matriz, se refiere al ndarray de NumPy.
<br>

In [5]:
import numpy as np
np.__version__

'2.2.6'

# ¿Por qué NumPy?


Algunas personas podrían preguntarse: *¿para que aprender una librería nueva?*

Eso es perfectamente razonable, pero ¿estás dispuesto a esperar muuuuucho más para que termine tu análisis? ¡Veamos qué tan rápido es realmente NumPy!

Para mostrar esto usaremos el comando mágico `% timeit` sobre el que puedes leer más en este link (https://ipython.readthedocs.io/en/stable/interactive/magics.html).

Echemos un vistazo a generar un vector de valores aleatorios de 10M y luego sumarlos todos usando Python y NumPy!

In [6]:
#Cargamos la librería
import numpy as np

x = np.random.randn(10000000) # generar números aleatorios

print("Ejecutamos la función sum() normal de Python")
%timeit sum(x)

print("Ejecutamos la función sum() de numpy")
%timeit np.sum(x)

Ejecutamos la función sum() normal de Python
721 ms ± 95.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Ejecutamos la función sum() de numpy
9.03 ms ± 504 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Esa fue una diferencia de aproximadamente unas **100 veces** y eso fue solo para una sola operación, de suma. ¡Imagínese si tuviera varios de esos corriendo todo el tiempo!

Numpy entonces? ...

# El ndarray <a name="ndarray"></a>
El ndarray es la columna vertebral de Numpy. Es un contenedor rápido y flexible para objetos de matriz N-dimensionales, generalmente utilizado para grandes conjuntos de datos en Python. Las matrices le permiten realizar operaciones matemáticas en bloques completos de datos utilizando una sintaxis similar a las operaciones equivalentes entre elementos escalares.

Aquí hay un ejemplo rápido de sus capacidades:

In [7]:
# crear una matriz 2x3 de valores aleatorios
data = np.random.randn(2,3)
data

array([[ 0.42178506, -0.39924632,  0.42962605],
       [-0.09750807,  0.33948561,  0.00821804]])

In [8]:
data *10 #Multiplicación x escalar

array([[ 4.21785056, -3.99246322,  4.29626053],
       [-0.97508069,  3.39485615,  0.08218044]])

Cada matriz tiene una forma, una tupla que indica el tamaño de cada dimensión y un dtype. Puede obtenerlos a través de los métodos respectivos:

In [9]:
# el tamaño de la matriz

data.shape

(2, 3)

In [10]:
# número de dimensiones de la matriz

data.ndim

2

In [11]:
# El tipo  almacenado en la matriz

data.dtype

dtype('float64')

## Crear matrices <a name="creating"> </a>
La forma más fácil y rápida de crear una matriz es desde una lista normal de Python.

In [12]:
data = [1.2, 5.2, 5, 7.8, 0.3]
arr = np.array(data)

arr

array([1.2, 5.2, 5. , 7.8, 0.3])

También es posible crear matrices multidimensionales de manera similar. Un ejemplo sería:
```python
data = [[1.2, 5.2, 5, 7.8, 0.3],
        [4.1, 7.2, 4.8, 0.1, 7.7]]
```
Intenten crear una matriz multidimensional a continuación y verifique su número de dimensiones:

In [13]:
data2 = [
        [1.2, 5.2, 5, 7.8, 0.3],
        [4.1, 7.2, 4.8, 0.1, 7.7]
        ]
arr2 = np.array(data2)
arr2

array([[1.2, 5.2, 5. , 7.8, 0.3],
       [4.1, 7.2, 4.8, 0.1, 7.7]])

In [14]:
arr2.ndim

2

También podemos crear una matriz llena de ceros

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Nuevamente, también es posible crear una matriz multidimensional pasando una tupla como argumento

In [16]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

NumPy también tiene un equivalente a la función de Python `range ()` pero se llama `arange ()`

In [17]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Aquí hay un resumen de los métodos más utilizados para crear matrices. tómalo como una referencia futura!

| Función | Descripción |
|----|:--|
| array  | Convierte los datos de entrada a un ndarray ya sea deduciendo un dtype <br> o especificando explícitamente un dtype; copia los datos de entrada por defecto.  |
| arange | Similar a la función `range`  pero devuelve un ndarray. |
| linspace | Devuelve números espaciados uniformemente en un intervalo especificado. |
| ones | Produce una matriz de todos los 1 con la forma y el tipo de datos. |
| ones_like | Similar a `ones` pero toma otra matriz y produce una matriz de 1s de la misma forma y tipo |
| zeros, zeros_like | Similar a `ones` pero produce una matriz de 0s |
| eye | Crea una matriz de identidad NxN cuadrada (1s en la diagonal y 0s en otra parte). |

## Data Types <a name="data"></a>
El tipo de datos o dtype es un objeto especial que contiene la información que la matriz necesita para interpretar un fragmento de memoria. Podemos especificarlo durante la creación de una matriz.

In [18]:
arr = np.array([1, 2, 3], dtype=np.float64)
arr.dtype

dtype('float64')

In [19]:
arr = np.array([1, 2, 3], dtype=np.int64)
arr.dtype

dtype('int64')

Un ndarray solo puede contener datos de **un** tipo de datos (dtype). Esto lo hace un poco menos flexible que una lista normal de Python, pero permite que NumPy se ejecute más rápido.


Se puede usar:
- `np.int64` para almacenar números enteros
- `np.float64` para almacenar números reales (con decimales)
- `np.bool` para almacenar valores `True` y `False` -> Deprecado

Al crear matrices en NumPy, el tipo se infiere (adivina), por lo que no necesita especificarlo explícitamente.

Similar a pandas, puede convertir (cast) una matriz de un dtype a otro usando el método `astype`:

In [20]:
arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [21]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

## Operaciones aritméticas <a name="arithmetic"> </a>
Ya has probado esto en los ejemplos anteriores, pero intentemos extenderlo.

Las matrices son importantes porque le permiten expresar operaciones por lotes sin tener que escribir bucles/loops "for"; esto se denomina **vectorización**.

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
A + A

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [24]:
A * A

array([[ 1,  4,  9],
       [16, 25, 36]])

In [25]:
A - A

array([[0, 0, 0],
       [0, 0, 0]])

Las operaciones aritméticas con escalares propagan el argumento escalar a cada elemento de la matriz:

In [26]:
A * 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [27]:
A ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [28]:
B = np.array([[1, 7, 4],[4, 12, 2]])
B

array([[ 1,  7,  4],
       [ 4, 12,  2]])

In [29]:
A > B

array([[False, False, False],
       [False, False,  True]])

### Broadcasting

La aplicación de operaciones aritméticas a matrices de diferentes tamaños se llama **broadcasting**.

In [30]:
# Ejemplo 1

A = np.ones((3,3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [31]:
B = np.arange(3)
B

array([0, 1, 2])

In [32]:
A + B

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [33]:
# Ejemplo 2

a = np.array([1, 2, 3])
b = 2
resultado = a + b
print(resultado)

[3 4 5]

¿qué pasó?

Estiramos 'B' para que coincida con la forma de 'A', el resultado es una matriz bidimensional

## Indexación y slicing
NumPy ofrece muchas opciones para indexar y segmentar. Casualmente, son muy similares a las que ya hemos visto.

In [34]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
A[5]

np.int64(5)

In [36]:
A[5:8]

array([5, 6, 7])

In [37]:
A[5:8] = 0
A

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

In [38]:
A_slice = A[5:8] #Tomar una slice
A_slice

array([0, 0, 0])

In [39]:
A[5:8] = [12, 17, 24] #Actualizarlo
A_slice #

array([12, 17, 24])

In [40]:
A

array([ 0,  1,  2,  3,  4, 12, 17, 24,  8,  9])

In [41]:
A_slice

array([12, 17, 24])

In [42]:
A_slice[:] = 0 # modificado
A # Original se mantiene
# A_slice

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

Con mas de 1 dimensión

In [43]:
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
C

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
C.shape

(3, 3)

In [45]:
C.size

9

In [46]:
C.ndim

2

Ahora que tenemos 2 dimensiones, necesitamos ingresar 2 índices para obtener un elemento específico de la matriz. Alternativamente, si ingresamos solo un índice, obtenemos toda la fila o columna de la matriz:

In [47]:
C[2]

array([7, 8, 9])

In [48]:
C[2][1]

np.int64(8)

In [49]:
C[2, 1]

np.int64(8)

In [50]:
C[:, 1]

array([2, 5, 8])

In [51]:
C[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
C[:2, 1:] # seleccione las primeras 2 filas, seleccione todas las columnas, desde la columna 1

array([[2, 3],
       [5, 6]])

In [53]:
C[2] # Seleccione la fila 2.

array([7, 8, 9])

In [54]:
C[2:, :] # Seleccione la fila 2.

array([[7, 8, 9]])

In [55]:
C[:, :2] # Seleccione todas las filas y 2 columnas

array([[1, 2],
       [4, 5],
       [7, 8]])

In [56]:
C[1:2, :2]  # Seleccione fila 1 hasta la fila 2-1, y seleccione 2 columnas

array([[4, 5]])

### Reformar y transponer matrices 
Podemos usar el método `reshape ()` para convertir los datos de una forma a otra, y podemos usar el atributo `T` para obtener la transposición de la matriz.

In [57]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [58]:
B = A.reshape((3,5))
B
# Probar B = A.reshape((3,8))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
B.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Funciones con ndarrays 
Ahora que hemos visto cómo crear y manipular ndarrays, veremos algunas de las muchas funciones que NumPy tiene que calcular con ellos. En particular,  *ufuncs*.

## Funciones universales 
NumPy proporciona funciones matemáticas familiares como sin, cos y exp. En NumPy, estas se llaman "funciones universales"*ufunc*. 

Dentro de NumPy, estas funciones operan por elementos en una matriz, produciendo una matriz como salida. Aquí hay un ejemplo de `sqrt` y` exp` ($e^x$):

In [60]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
np.sqrt(A)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [62]:
np.exp(A)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

Otras funciones universales toman 2 matrices como entrada. Estas se llaman funciones *binarias*.

Por ejemplo, `maximum ()` selecciona los valores más grandes de dos matrices de entrada.

In [63]:
x = np.random.randn(10)
x

array([-0.77096768,  0.9278741 , -0.09872717,  0.35502311,  1.88204602,
       -0.32121377,  1.77869958,  1.60911897,  1.07490981, -1.7819448 ])

In [64]:
y = np.random.randn(10)
y

array([ 0.36497977, -0.05505849, -1.3268167 ,  0.12447265, -1.42024071,
       -0.90696684, -0.03717267,  0.84265467, -0.05442322,  0.5720266 ])

In [65]:
np.maximum(x, y)

array([ 0.36497977,  0.9278741 , -0.09872717,  0.35502311,  1.88204602,
       -0.32121377,  1.77869958,  1.60911897,  1.07490981,  0.5720266 ])

Aquí hay una lista de útiles *ufuncs* en NumyPy:

*No necesitas memorizarlos. Esto es solo una referencia*
### Funciones unitarias (acepta un argumento)

| Función | Descripción |
|----|----|
| abs, fabs | Calcule el valor absoluto para valores enteros,  floats o complejos. <br> Use fabs como una alternativa más rápida para datos de valores no complejos|
| sqrt | Calcule la raíz cuadrada de cada elemento. Equivalente a ** 0.5 |
| exp | Compute the exponent ex of each element |
| log, log10, log2, log1p | Logaritmo natural (base e), log base 10, log base 2 y log (1 + x), respectivamente|
| cos, cosh, sin, sinh, tan, tanh | Funciones trigonométricas regulares e hiperbólicas. |

### Funciones binarias (acepta 2 argumentos)
| Función | Descripción |
| ---- | ---- |
| add | Agregar elementos correspondientes en matrices|
| subtract | Restar elementos en la segunda matriz de la primera matriz |
| multiply | Multiplicar elementos de matriz |
| divide, floor_divide | División o división de piso (truncando el resto) |
| mod | Resto de división |
| power | Elevar elementos en la primera matriz a las potencias indicadas en la segunda matriz |
| maximum | máximo. fmax ignora NaN |
| minimum | mínimo. fmin ignora NaN |

## Funciones de matriz completa <a name="whole"> </a>
Además de ufuncs, que operan elemento por elemento, hay muchas funciones que operan en el conjunto de una matriz a la vez.

NumPy ofrece un conjunto de funciones matemáticas que calculan estadísticas sobre una matriz completa:

In [66]:
B = np.random.randn(5, 4)
B

array([[ 0.16521818, -0.93490433, -0.04943323,  1.47525749],
       [-0.08721674,  0.6503176 , -0.80131809,  0.00358625],
       [ 0.00575268, -0.39018393, -1.68284501,  2.05847674],
       [-1.11315144,  0.73850794,  1.06012792,  1.05137646],
       [ 0.65298735, -0.63392225,  0.40051743,  1.23575553]])

In [67]:
B.mean()

np.float64(0.19024532775341246)

In [68]:
np.mean(B)

np.float64(0.19024532775341246)

In [69]:
B.sum()

np.float64(3.8049065550682495)

In [70]:
B.mean(axis=1) # Calcule la media en la dirección de la columna (eje 1) (es decir, la media de cada fila)

array([ 0.16403453, -0.05865774, -0.00219988,  0.43421522,  0.41383451])

In [71]:
B.mean(axis=0) # Calcule la media en la dirección de las filas (eje 0) (es decir, la media de cada columna)

array([-0.07528199, -0.11403699, -0.2145902 ,  1.1648905 ])

Similar a las lista de Python, los arreglos NumyPy tienen una función para ordenarlos en el lugar:

In [72]:
A = np.random.randn(10)
A

array([ 0.83596864,  0.34191865,  0.99053818,  1.83592121,  1.37245889,
        0.34032219,  2.07802981, -1.73230811, -1.38729074, -0.22401585])

In [73]:
A.sort()
A

array([-1.73230811, -1.38729074, -0.22401585,  0.34032219,  0.34191865,
        0.83596864,  0.99053818,  1.37245889,  1.83592121,  2.07802981])

In [74]:
C = np.array([[100, 20, 30], [4, 5, 6], [7, 8, 9]])
C

array([[100,  20,  30],
       [  4,   5,   6],
       [  7,   8,   9]])

In [75]:
C.sort()
C

array([[ 20,  30, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [76]:
C = np.array([[100, 20, 30], [4, 5, 6], [7, 8, 9]])
C

array([[100,  20,  30],
       [  4,   5,   6],
       [  7,   8,   9]])

In [77]:
C.sort(axis=1)
C

array([[ 20,  30, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [78]:
C = np.array([[100, 20, 30], [4, 5, 6], [7, 8, 9]])
C

array([[100,  20,  30],
       [  4,   5,   6],
       [  7,   8,   9]])

In [79]:
C.sort(axis=0)
C

array([[  4,   5,   6],
       [  7,   8,   9],
       [100,  20,  30]])

## Álgebra lineal <a name="linear"> </a>
NumyPy ofrece un conjunto de operaciones estándar de álgebra lineal, como la multiplicación de matrices, descomposiciones y determinantes. Empecemos con lo básico. En numpy, la multiplicación de matrices se realiza con `@`:

In [80]:
A = np.random.randn(3,1)
A

array([[-1.06399388],
       [-0.9675699 ],
       [ 1.54901824]])

In [81]:
B = np.random.randn(1,3)
B

array([[-0.16982857, -0.37514271,  0.50998249]])

In [82]:
A @ B

array([[ 0.18069656,  0.39914955, -0.54261825],
       [ 0.16432102,  0.3629768 , -0.49344371],
       [-0.26306756, -0.5811029 ,  0.78997218]])

In [83]:
np.matmul(A, B)

array([[ 0.18069656,  0.39914955, -0.54261825],
       [ 0.16432102,  0.3629768 , -0.49344371],
       [-0.26306756, -0.5811029 ,  0.78997218]])

Hay algunas funciones disponibles en NumPy  para trabajar con matrices:

| Función | Descripción |
| --- | --- |
| diag | Devuelve los elementos diagonales (o fuera de diagonal) de una matriz cuadrada como una matriz 1D, o convierta una matriz 1D en una matriz cuadrada con ceros fuera de la diagonal |
| dot | Multiplicación de matrices |
| trace | Calcula la suma de los elementos diagonales. |

Multiplicación de Matrices

In [84]:
# Multiplicacion de matrices
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [85]:
a @ b

array([[37, 40],
       [85, 92]])

In [86]:
np.matmul(a, b)

array([[37, 40],
       [85, 92]])

Suma de elementos diagonales

In [87]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
np.trace(a)

np.int64(15)

Obtener la diagonal

In [89]:
# Obtener la diagonal de una matriz
np.diag(a)

array([1, 5, 9])

## Condicional
La función `np.where` es muy útil para realizar selecciones condicionales y se utiliza tanto en el contexto de arrays como en DataFrames y Series de pandas.

In [90]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [91]:
# Entrega los Indices que cumplen con la(s) condiciones.
resultado = np.where(a > 3)
print (resultado)

(array([3, 4]),)

In [92]:
# Devuelve una matriz con el resultado 
resultado = np.where(a > 3, 'Mayor', 'Menor o igual')
print (resultado)

['Menor o igual' 'Menor o igual' 'Menor o igual' 'Mayor' 'Mayor']

## Su uso en en Pandas

In [93]:
import pandas as pd
import numpy as np

# Crear un DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50]
})
df

   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [94]:
# Crear una nueva columna basada en una condición con np.where

df['C'] = np.where(df['A'] > 3, 'Mayor', 'Menor o igual')
print(df)

   A   B              C
0  1  10  Menor o igual
1  2  20  Menor o igual
2  3  30  Menor o igual
3  4  40          Mayor
4  5  50          Mayor

In [95]:
# Crear una nueva columna basada en una condición con np.where con Multiples condiciones

df['D'] = np.where(     (df['A'] > 3) & (df['B'] < 50)    , 'Cumple', 'No cumple')
print(df)

   A   B              C          D
0  1  10  Menor o igual  No cumple
1  2  20  Menor o igual  No cumple
2  3  30  Menor o igual  No cumple
3  4  40          Mayor     Cumple
4  5  50          Mayor  No cumple

In [96]:
df['D'] = np.where((df['D']=="Cumple"), 'Bien', 'Mal')
print(df)

   A   B              C     D
0  1  10  Menor o igual   Mal
1  2  20  Menor o igual   Mal
2  3  30  Menor o igual   Mal
3  4  40          Mayor  Bien
4  5  50          Mayor   Mal

### Ventajas de np.where() en pandas y NumPy:
Permite realizar selecciones y asignaciones condicionales de manera vectorizada, lo que significa que es mucho más rápido que usar bucles.

In [97]:
import pandas as pd
import numpy as np

# Crear un DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3, 4, 5]
})

df['C'] = np.where(    df['A'] > 3, 'Mayor', '')

df

   A      C
0  1
1  2
2  3
3  4  Mayor
4  5  Mayor